# Generated by Django 2.2.5 on 2019-09-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190913_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_volontier',
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
        migrations.DeleteModel(
            name='OrganizationProfile',
        ),
    ]
