# Generated by Django 2.2.5 on 2019-09-13 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190913_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizator',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=5000)),
                ('Logo', models.ImageField(upload_to='', verbose_name='Logo')),
                ('country', models.TextField(max_length=30)),
                ('city', models.TextField(max_length=30)),
                ('address', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.TextField(max_length=100)),
                ('last_name', models.TextField(max_length=100)),
                ('county', models.TextField(max_length=30)),
                ('city', models.TextField(max_length=30)),
                ('User photo', models.ImageField(upload_to='', verbose_name='User photo')),
                ('rating', models.FloatField(default=0)),
                ('description', models.TextField(max_length=5000)),
                ('employment_situation', models.TextField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_organizator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_volunteer',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='VolunteerProfile',
        ),
    ]
