# Generated by Django 2.2.5 on 2019-09-13 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.TextField(max_length=40)),
                ('instagram_user_name', models.TextField(max_length=100)),
                ('facebook_link', models.TextField(max_length=100)),
                ('vk_link', models.TextField(max_length=100)),
                ('email_adress', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=5000)),
                ('Logo', models.ImageField(upload_to='', verbose_name='Logo')),
                ('country', models.TextField(max_length=30)),
                ('city', models.TextField(max_length=30)),
                ('address', models.TextField(max_length=100)),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Contacts')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=100)),
                ('last_name', models.TextField(max_length=100)),
                ('county', models.TextField(max_length=30)),
                ('city', models.TextField(max_length=30)),
                ('User photo', models.ImageField(upload_to='', verbose_name='User photo')),
                ('rating', models.FloatField(default=0)),
                ('description', models.TextField(max_length=5000)),
                ('employment_situation', models.TextField(max_length=100)),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Contacts')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_name', models.TextField(max_length=50)),
                ('date_range', models.TextField(max_length=21)),
                ('description', models.TextField(max_length=5000)),
                ('competitions_keywords', models.TextField(max_length=5000)),
                ('event_name', models.TextField(max_length=1000)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Organization')),
            ],
        ),
    ]
