# Generated by Django 2.2.5 on 2019-09-14 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190914_0027'),
        ('users', '0006_auto_20190914_0002'),
    ]

    operations = [
    ]
