# Generated by Django 2.2.5 on 2019-09-14 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190914_0412'),
        ('users', '0008_merge_20190914_0231'),
    ]

    operations = [
    ]
