# Generated by Django 2.2.5 on 2019-09-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
