# Generated by Django 2.2.5 on 2019-09-13 21:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190913_1807'),
        ('univol', '0002_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.IntegerField()),
                ('respond_date', models.DateTimeField(default=datetime.datetime(2019, 9, 13, 21, 11, 1, 901896))),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Volunteer')),
            ],
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
