# Generated by Django 2.2.5 on 2019-09-13 22:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('univol', '0003_auto_20190913_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='responds',
            name='vacancy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='univol.Vacancy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='responds',
            name='respond_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
