# Generated by Django 2.2.5 on 2019-09-14 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univol', '0004_auto_20190913_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='competitions_keywords',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='date_range',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 1, 46, 23, 787413)),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='event_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy_name',
            field=models.CharField(max_length=50),
        ),
    ]
