# Generated by Django 2.2.5 on 2019-09-14 02:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('univol', '0005_auto_20190914_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='date_range',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 2, 15, 51, 966014)),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='organization',
            field=models.ForeignKey(default=users.models.CustomUser, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
