# Generated by Django 2.2.5 on 2019-09-14 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univol', '0008_auto_20190914_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='date_range',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 3, 11, 12, 87011)),
        ),
    ]
