# Generated by Django 2.2.5 on 2019-09-14 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univol', '0010_auto_20190914_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='date_range',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 4, 24, 27, 155419)),
        ),
    ]
